
sql:
  namespace: mysql

  secret:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_USER: "app_user"
    MYSQL_PASSWORD: "1234"

  statefulSet:
    replicas: 2

  image:
    repository: mysql
    version: 8.0

  pvc:
    resources:
      requests:
        storage: "2Gi"

  nodeAffinity:
    key: "app"
    values:
      - mysql

  podAntiAffinity:
    key: "app"
    operator: "In"
    values:
      - mysql

  tolerations:
  - key: "app"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
