apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.sql.namespace }}
type: Opaque
data:
  {{- range $k, $v := .Values.sql.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}