apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.common.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ .Values.serviceAccountName }}-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccountName }}-binding
  namespace: {{ .Values.common.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccountName }}-role
  apiGroup: rbac.authorization.k8s.io
